#ifndef ACTUATORS_CONFIG_H
#define ACTUATORS_CONFIG_H

#define DEFAULT_HEIGHT 0
  
#define DEFAULT_OPENING 0

#define LEFT_PUSHER_DEPLOYED 0
#define LEFT_PUSHER_RETRACTED 150

#define RIGHT_PUSHER_DEPLOYED 190
#define RIGHT_PUSHER_RETRACTED 30

// #define MAGNETS_PIN 99
#endif