#ifndef ACTUATORS_CONFIG_H
#define ACTUATORS_CONFIG_H

#define GRABBER_HEIGHT_SERVO_PIN 99
#define DEFAULT_HEIGHT 0

#define GRABBER_OPENING_SERVO_PIN 99
#define DEFAULT_OPENING 0

#define LEFT_PUSHER_SERVO_PIN 9
#define LEFT_PUSHER_DEPLOYED 150
#define LEFT_PUSHER_RETRACTED 0

#define RIGHT_PUSHER_SERVO_PIN 10
#define RIGHT_PUSHER_DEPLOYED 180
#define RIGHT_PUSHER_RETRACTED 30

// #define MAGNETS_PIN 99
#endif